spring.application.name=project_module3
server.port=8080

# Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/course_db
spring.datasource.username=postgres
spring.datasource.password=vietanh2k5
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=super-secret-key-should-be-at-least-256-bits-long
#24h
jwt.expiration=86400000
#7 days
jwt.refresh-expiration=604800000

# LOGGING
logging.level.root=INFO
logging.level.com.example.coursems=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE